// Generated by CoffeeScript 1.8.0
(function() {
  var code, ends, highlight, html, liquid, liquidAfter, liquidBefore, liquidCenter, pattern, syntax, _i, _len, _ref;

  code = "console.log(\"fwei\");";

  html = "";

  syntax = {
    "patterns": [
      {
        'begin': '"',
        'beginCaptures': {
          '0': {
            'name': 'punctuation.definition.string.begin.js'
          }
        },
        'end': '"',
        'endCaptures': {
          '0': {
            'name': 'punctuation.definition.string.end.js'
          }
        },
        'name': 'string.quoted.double.js',
        'patterns': [
          {
            'match': '\\\\(x\\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)',
            'name': 'constant.character.escape.js'
          }
        ]
      }, {
        'match': '\\b(console)\\b',
        'name': 'entity.name.type.object.js.firebug'
      }
    ]
  };

  liquidBefore = "var nibe = function(){\n  switch (false) {\n      case !(code === \"\"):\n        return html;\n        break;";

  liquidAfter = "    case !/^./.test(code):\n      html += RegExp.lastMatch;\n      code = code.replace(/^./, \"\");\n      highlight(liquid);\n      break;\n}\n}";

  liquidCenter = "";

  ends = [];

  _ref = syntax["patterns"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    pattern = _ref[_i];
    if (pattern["begin"]) {
      liquidCenter += "case !/^" + pattern["begin"] + "/.test(code):\n  html += \"<span class=\\\"" + pattern["name"] + "\\\">\"+RegExp.lastMatch;\n  code = code.replace(/^" + pattern["begin"] + "/, \"\");\n  highlight(liquid);\n  break;\n";
    }
    if (pattern["match"]) {
      liquidCenter += "case !/^" + pattern["match"] + "/.test(code):\n  html += \"<span class=\\\"" + pattern["name"] + "\\\">\"+RegExp.lastMatch+\"</span>\";\n  code = code.replace(/^" + pattern["match"] + "/, \"\");\n  highlight(liquid);\n  break;\n";
    }
  }

  liquid = liquidBefore + liquidCenter + liquidAfter;

  console.log(liquidCenter);

  highlight = function(rule) {
    eval(rule);
    nibe();
    return html;
  };

  console.log(highlight(liquid));

}).call(this);
