// Generated by CoffeeScript 1.9.0
(function() {
  var fileOpen, fs, path;

  fs = require("fs");

  path = require("path");

  fileOpen = function(path) {
    return fs.readFile(path, function(err, text) {
      return $("#code").val(text);
    });
  };

  $(function() {
    return $("#folderDialog").change(function(e) {
      var $dfFile, $dfFolder, $documentFragment, $project, folder;
      folder = $('#folderDialog')[0].files[0];
      $project = $("<ul>").attr("id", "project");
      $documentFragment = $(document.createDocumentFragment());
      $dfFolder = $(document.createDocumentFragment());
      $dfFile = $(document.createDocumentFragment());
      fs.readdir(folder.path, function(err, files) {
        var file, filePath, _i, _len;
        if (err) {
          throw err;
        }
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          filePath = path.join(folder.path, file);
          if (fs.statSync(filePath).isDirectory()) {
            $dfFolder.append($("<li>").addClass("folder").text(file).attr("data-path", filePath));
          } else {
            $dfFile.append($("<li>").addClass("file").text(file).attr("data-path", filePath));
          }
        }
        $project.append($dfFolder);
        $project.append($dfFile);
        $documentFragment.append($project);
        return $("#sidebar").html($documentFragment);
      });
      $(document).on("click", ".folder", function() {
        return console.log($(this).data("path"));
      });
      return $(document).on("click", ".file", function() {
        return fileOpen($(this).data("path"));
      });
    });
  });

}).call(this);
