// Generated by CoffeeScript 1.9.0
(function() {
  var f;

  f = "";

  switch (false) {
    case !/^./.test(f):
      console.log(".");
      break;
    case !/^a/.test(f):
      console.log("a");
  }

}).call(this);
