// Generated by CoffeeScript 1.9.0
(function() {
  var test;

  test = require("../hilight").test;

  describe("test", function() {
    return it("tests", function() {
      return expect(test(2, 3)).toEqual(5);
    });
  });

}).call(this);
